apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cbpcc9hha-go 
  janus-idp.io/tekton: cbpcc9hha-go
  backstage.io/kubernetes-id: cbpcc9hha-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cbpcc9hha-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml